### ISSUE TITLE
Неправильный тип переменной

### ISSUE THREAD

**Issue by AnPogrebnyak** [MarharytaTsepiennikova/prog.kiev.ua#1]
Что будет, если добавить в массив три элемента, значение каждого - один миллиард?
https://github.com/MarharytaTsepiennikova/prog.kiev.ua/blob/44c2a1dc01d82fdc5607f1c450422738393ef266/Homework3_4.java#L9

**Comment by MarharytaTsepiennikova** [comment]
исправлено на long

**Comment by AnPogrebnyak** [comment]
Не вижу

**Comment by MarharytaTsepiennikova** [comment]
https://github.com/MarharytaTsepiennikova/homework_3/blob/master/src/Homework3_4.java стали лонги

**Comment by AnPogrebnyak** [comment]
ок
