### ISSUE TITLE
Зачем тут цикл?

### ISSUE THREAD

**Issue by AnPogrebnyak** [MarharytaTsepiennikova/prog.kiev.ua#3]
https://github.com/MarharytaTsepiennikova/prog.kiev.ua/blob/44c2a1dc01d82fdc5607f1c450422738393ef266/Homework3_5_2.java#L19

**Comment by MarharytaTsepiennikova** [comment]
и правда. увлеклась

**Comment by AnPogrebnyak** [comment]
Ну так исправь код )

**Comment by MarharytaTsepiennikova** [comment]
https://github.com/MarharytaTsepiennikova/homework_3/blob/master/src/Homework3_5_2.java тут этот кусок. из предыдущего репозитория потерла задания, а то путаница сплошная

**Comment by AnPogrebnyak** [comment]
ок
