### ISSUE TITLE
Преобразуй репозиторий в проект

### ISSUE THREAD

**Issue by AnPogrebnyak** [MarharytaTsepiennikova/prog.kiev.ua#4]
Закоммить, пожалуйста всю структуру проекта в IDE.
Не коммить в репозиторий: конфигурационные файлы и откомпилированный код.
То есть в репозиторий должна попасть только корневая папка проекта и в ней папка src с исходным кодом.

**Comment by MarharytaTsepiennikova** [comment]
готово

**Comment by AnPogrebnyak** [comment]
Неправильно: 

> То есть в репозиторий должна попасть только корневая папка проекта и в ней папка src с исходным кодом.

Где папка src?

**Comment by MarharytaTsepiennikova** [comment]
https://github.com/MarharytaTsepiennikova/homework_3 все домашки к 3му занятию в этом проекте

**Comment by AnPogrebnyak** [comment]
ок
